# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FlappyBirdTui < Formula
  desc "Terminal-based Flappy Bird clone built with Go and Bubble Tea"
  homepage "https://github.com/takish/flappy-bird-tui"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/takish/flappy-bird-tui/releases/download/v0.2.1/flappy-bird-tui_0.2.1_darwin_amd64.tar.gz"
      sha256 "fd56b07a59d91a3b1e7f46bd0c36c0eb620eb43f838eb75cce4cf6cefb55f119"

      def install
        bin.install "flappy-bird-tui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/takish/flappy-bird-tui/releases/download/v0.2.1/flappy-bird-tui_0.2.1_darwin_arm64.tar.gz"
      sha256 "71090b30d3c562196cd2167144f92bdb1db5bc98bc44fc43372ad3f19b264635"

      def install
        bin.install "flappy-bird-tui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/takish/flappy-bird-tui/releases/download/v0.2.1/flappy-bird-tui_0.2.1_linux_amd64.tar.gz"
      sha256 "f1eecc131dc63ca807953f8915a2f328488764e26a347c100fa40763b85a84cb"
      def install
        bin.install "flappy-bird-tui"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/takish/flappy-bird-tui/releases/download/v0.2.1/flappy-bird-tui_0.2.1_linux_arm64.tar.gz"
      sha256 "a471a5e6550f50f68cf02db48a2b987de487c7040fa88679fb1b4f3cd2261e8c"
      def install
        bin.install "flappy-bird-tui"
      end
    end
  end

  test do
    system "#{bin}/flappy-bird-tui --version"
  end
end
